version: 2
updates:
- package-ecosystem: bundler
  target-branch: "main"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  target-branch: "main"
  directory: "/omnibus"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  target-branch: "inspec-5"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  target-branch: "inspec-5"
  directory: "/omnibus"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  target-branch: "inspec-7"
  directory: "/"
  schedule:
    interval: daily
<<<<<<< HEAD
  open-pull-requests-limit: 10
=======
  open-pull-requests-limit: 10
# - package-ecosystem: bundler
#   target-branch: "inspec-7"
#   directory: "/omnibus"
#   schedule:
#     interval: daily
#   open-pull-requests-limit: 10
>>>>>>> f4d52a52c (CHEF-18302 Remove omnibus support for InSpec (#7249))
