---
driver:
  name: dokken
  chef_version: 14.3.37
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken
  client_rb:
    data_collector.server_url: <%= ENV['COLLECTOR_URL'] %>
    data_collector.token: <%= ENV['COLLECTOR_TOKEN'] %>
    ssl_verify_mode: :verify_none
    verify_api_cert: false

verifier:
  name: inspec
  sudo: true
  attributes:
    verifier_attribute: 'Attribute Override!'

platforms:
- name: ubuntu-12.04
  driver:
    image: ubuntu:12.04
- name: ubuntu-14.04
  driver:
    image: ubuntu:14.04
- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    intermediate_instructions:
    - RUN /usr/bin/apt-get update
    pid_one_command: /bin/systemd
- name: centos-6.6
  driver:
    image: centos:6.6
- name: centos-6.8
  driver:
    image: centos:6.8
    intermediate_instructions:
      - RUN yum install -y initscripts
- name: centos-7
  driver:
    image: centos:7
    pid_one_command: /usr/lib/systemd/systemd
- name: oracle-6.7
  driver:
    image: oraclelinux:6.7
- name: oracle-7.2
  driver:
    image: oraclelinux:7.2
    pid_one_command: /usr/lib/systemd/systemd
- name: debian-7
  driver:
    image: debian:7.11
    intermediate_instructions:
    - RUN /usr/bin/apt-get update
    # running it within the chef recipe is too late :-(
    - RUN /usr/bin/apt-get install -y procps lsb-release
- name: debian-8
  driver:
    image: debian:8.5
    intermediate_instructions:
    - RUN /usr/bin/apt-get update
    # running it within the chef recipe is too late :-(
    - RUN /usr/bin/apt-get install -y procps lsb-release
    pid_one_command: /bin/systemd
- name: fedora-23
  driver:
    image: fedora:23
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
    - RUN dnf install -y yum
- name: fedora-24
  driver:
    image: fedora:24
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
    - RUN dnf install -y yum

suites:
- name: default
  run_list:
  - recipe[os_prepare]
  - recipe[audit]
  - recipe[apt]
  - recipe[yum]
  verifier:
    inspec_tests:
      - test/integration/default
  attributes:
    audit:
      attributes:
        audit_attribute: 'Attribute Override!'
      insecure: true
      reporter: ['json-file','chef-automate']
      fetcher: 'chef-automate'
      json_file:
        location: /tmp/json_export.json
      profiles:
        - name: integration
          url: https://github.com/inspec/inspec-integration-profile/archive/master.zip
    osprepare:
      docker: true
      application: false
