---
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4
  Exclude:
  - Gemfile
  - Rakefile
  - 'test/**/*'
  - 'lib/plugins/*/test/**/*'
  - 'lib/plugins/inspec-init/templates/**/*'
  # This is delicate; we want to include examples/plugins/*/lib
  # but not anything else.
  - 'examples/*profile*/**/*'
  - 'examples/kitchen*/**/*'
  - 'examples/inheritance/**/*'
  - 'examples/custom-resource/**/*'
  - 'examples/plugins/*/test/**/*'
  - 'vendor/**/*'
  - 'lib/bundles/inspec-init/templates/**/*'
  - 'www/demo/**/*'
  - 'kitchen/**/*'
AlignParameters:
  Enabled: true
BlockDelimiters:
  Enabled: false
Documentation:
  Enabled: false
EmptyLinesAroundBlockBody:
  Enabled: false
FrozenStringLiteralComment:
  Enabled: false
HashSyntax:
  Enabled: true
LineLength:
  Enabled: false
Layout/AlignHash:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: lf
Layout/SpaceAroundOperators:
  Enabled: false
MethodLength:
  Max: 40
Metrics/AbcSize:
  Max: 33
Metrics/BlockLength:
  Max: 50
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 11
NumericLiterals:
  MinDigits: 10
Performance/RegexpMatch:
  Enabled: false
Security/YAMLLoad:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/FileName:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MethodMissing:
  Enabled: false
Style/MultilineIfModifier:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/Not:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': ()
    '%q': '{}'
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': '{}'
    '%W': ()
    '%x': ()
Style/PredicateName:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
Style/UnlessElse:
  Enabled: false
