AllCops:
  TargetRubyVersion: 3.1 # this should match the required ruby in the gemspec
  Exclude:
    - 'test/kitchen/**/*'
    - 'test/integration/**/controls/**/*.rb'
    - 'test/fixtures/profiles/**/*.rb'
    - 'test/fixtures/config_dirs/**/*.rb'
    - 'lib/plugins/inspec-init/templates/plugins/inspec-plugin-template/**/*'
    - 'examples/**/*.rb'
    - 'vendor/bundle/**/*'
Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument
