driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ['..', '/home/vagrant/inspec']

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: centos-7.1
    run_list: yum-epel::default
  - name: centos-6.6
    run_list: yum-epel::default
  - name: debian-7.8
    run_list: apt::default
  - name: debian-6.0.10
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-12.04
    run_list: apt::default

suites:
  - name: default
    run_list: omnibus::default
    attributes:
      omnibus:
        build_user:          vagrant
        build_user_group:    vagrant
        build_user_password: vagrant
        install_dir:         /opt/inspec
