# encoding: utf-8
source 'https://rubygems.org'

# Install omnibus
# Sadly due to an ongoing msys2 issue, producing windows builds requires
# the two branches below.
# gem 'omnibus', github: 'chef/omnibus', branch: 'ksubrama/gcc_investigate'

# Use Chef's software definitions. It is recommended that you write your own
# software definitions, but you can clone/fork Chef's to get you started.
# gem 'omnibus-software', github: 'chef/omnibus-software', branch: 'ksubrama/ruby23'

# Use entries from chef's Gemfile
gem 'omnibus', github: 'chef/omnibus'
gem 'omnibus-software', github: 'chef/omnibus-software'
gem 'license_scout', github: 'chef/license_scout'

# This development group is installed by default when you run `bundle install`,
# but if you are using Omnibus in a CI-based infrastructure, you do not need
# the Test Kitchen-based build lab. You can skip these unnecessary dependencies
# by running `bundle install --without development` to speed up build times.
group :development do
  # Use Berkshelf for resolving cookbook dependencies
  gem 'berkshelf', '~> 4.3'

  # Use Test Kitchen with Vagrant for converging the build environment
  gem 'test-kitchen',    '~> 1.9'
  gem 'kitchen-vagrant', '~> 0.19'
  gem 'winrm-fs', '~> 0.4'
end
