source "https://rubygems.org"

gem "omnibus", github: ENV.fetch("OMNIBUS_GITHUB_REPO", "chef/omnibus"), branch: ENV.fetch("OMNIBUS_GITHUB_BRANCH", "main")
gem "omnibus-software", github: ENV.fetch("OMNIBUS_SOFTWARE_GITHUB_REPO", "chef/omnibus-software"), branch: ENV.fetch("OMNIBUS_SOFTWARE_GITHUB_BRANCH", "main")
gem "artifactory"

if Gem::Version.new(RUBY_VERSION) <= Gem::Version.new("3.1.0")
  gem "ffi", ">= 1.15.5", "< 1.17.0"
else
  gem "ffi", ">= 1.17.0"
end

gem "ffi-yajl", "2.6.0"

# This development group is installed by default when you run `bundle install`,
# but if you are using Omnibus in a CI-based infrastructure, you do not need
# the Test Kitchen-based build lab. You can skip these unnecessary dependencies
# by running `bundle config set --local without development` to speed up build times.
group :development do
  # Use Berkshelf for resolving cookbook dependencies
  gem "berkshelf", ">= 7.0"

  # Use Test Kitchen with Vagrant for converging the build environment
  gem "kitchen-vagrant", ">= 1.3.1"
  gem "test-kitchen", ">= 1.23"
  gem "winrm-fs", "~> 1.0"
end