# encoding: utf-8
source 'https://supermarket.chef.io'

metadata

cookbook 'delivery-truck',
         git: 'https://github.com/chef-cookbooks/delivery-truck.git',
         branch: 'master'

cookbook 'delivery-sugar',
         git: 'https://github.com/chef-cookbooks/delivery-sugar.git',
         branch: 'master'

cookbook 'delivery-sugar-extras',
         git: 'https://github.com/chef-cookbooks/delivery-sugar-extras.git',
         branch: 'master'
