$stderr.puts "-----------------------------------"
$stderr.puts "        TEST ENVIRONMENT           "
$stderr.puts "-----------------------------------"
$stderr.puts "    Docker: #{!ENV['DOCKER'].nil?}"
$stderr.puts "   OS name: #{os[:name] || 'unknown' }"
$stderr.puts "OS release: #{os[:release] || 'unknown'}"
$stderr.puts " OS family: #{os[:family] || 'unknown'}"
$stderr.puts "-----------------------------------"
