source "https://rubygems.org"
gem "inspec-bin", git: "https://github.com/inspec/inspec", branch: "team/gem-based-resource-packs"
gem "inspec", git: "https://github.com/inspec/inspec", branch: "team/gem-based-resource-packs"
