module DeprecatedCloudResourcesList
  CLOUD_RESOURCES_DEPRECATED = %i{
    aws_billing_report
    aws_billing_reports
    aws_cloudtrail_trail
    aws_cloudtrail_trails
    aws_cloudwatch_alarm
    aws_cloudwatch_log_metric_filter
    aws_config_delivery_channel
    aws_config_recorder
    aws_ec2_instance
    aws_ebs_volume
    aws_ebs_volumes
    aws_flow_log
    aws_ec2_instances
    aws_ecs_cluster
    aws_eks_cluster
    aws_elb
    aws_elbs
    aws_iam_access_key
    aws_iam_access_keys
    aws_iam_group
    aws_iam_groups
    aws_iam_password_policy
    aws_iam_policies
    aws_iam_policy
    aws_iam_role
    aws_iam_root_user
    aws_iam_user
    aws_iam_users
    aws_kms_key
    aws_kms_keys
    aws_rds_instance
    aws_route_table
    aws_route_tables
    aws_s3_bucket
    aws_s3_bucket_object
    aws_s3_buckets
    aws_security_group
    aws_security_groups
    aws_sns_subscription
    aws_sns_topic
    aws_sns_topics
    aws_sqs_queue
    aws_subnet
    aws_subnets
    aws_vpc
    aws_vpcs
    azure_generic_resource
    azure_resource_group
    azure_virtual_machine
    azure_virtual_machine_data_disk
  }.freeze
end
