# encoding: utf-8
source 'https://rubygems.org'

gem 'inspec', path: '../../.'
gem 'r-train', git: 'git@github.com:chef/train.git'

group :test do
  gem 'bundler', '~> 1.5'
  gem 'minitest', '~> 5.5'
  gem 'rake', '~> 10'
  gem 'rubocop', '~> 0.33.0'
  gem 'simplecov', '~> 0.10'
end

group :integration do
  gem 'berkshelf', '~> 4.0'
  gem 'test-kitchen', '~> 1.4'
  gem 'kitchen-vagrant'
  gem 'kitchen-puppet'
  gem 'librarian-puppet'
  gem 'kitchen-inspec', git: 'git@github.com:chef/kitchen-inspec.git'
  gem 'concurrent-ruby', '~> 0.9'
end
