source "https://rubygems.org"

gem "slim", ">= 3.0"

# Middleman Gems
gem "middleman", ">= 4.0.0"
gem "middleman-autoprefixer"
gem "middleman-livereload"
gem "middleman-search_engine_sitemap", "~> 1.4"
gem "middleman-sprockets", ">= 4.0.0"
gem "middleman-syntax"
gem "redcarpet"

# Needed to fetch contrib resource packs, etc.
gem "git", "~> 1.4"

# Build process requirements
gem "inspec", path: ".."
gem "rake"

# Ability to flush the cache during a deploy
gem "fastly"
