##
# Now that resources are lazily loaded, this file is ONLY here for one
# reason at this point, to load all the resources in order to populate
# the registry for `inspec shell`'s `help commands`. There has to be a
# cheaper way to do this, but this will do for now.
#
# NOTE: I intentionally didn't convert this to a loop over a simple
# glob so this remains a sort of manifest for our resources.

require_relative "resource"

# Detect if we are running the stripped-down inspec-core
# This relies on AWS being stripped from the inspec-core gem
inspec_core_only = ENV["NO_AWS"] || !File.exist?(File.join(File.dirname(__FILE__), "..", "resource_support", "aws.rb"))

# Do not attempt to load cloud resources if we are in inspec-core mode
unless inspec_core_only
  require_relative "../resource_support/aws"
  require "resources/azure/azure_backend.rb"
  require "resources/azure/azure_generic_resource.rb"
  require "resources/azure/azure_resource_group.rb"
  require "resources/azure/azure_virtual_machine.rb"
  require "resources/azure/azure_virtual_machine_data_disk.rb"
end

require_relative "resources/aide_conf"
require_relative "resources/apache"
require_relative "resources/apache_conf"
require_relative "resources/apt"
require_relative "resources/audit_policy"
require_relative "resources/auditd"
require_relative "resources/auditd_conf"
require_relative "resources/bash"
require_relative "resources/bond"
require_relative "resources/bridge"
require_relative "resources/chocolatey_package"
require_relative "resources/command"
require_relative "resources/cran"
require_relative "resources/cpan"
require_relative "resources/crontab"
require_relative "resources/dh_params"
require_relative "resources/directory"
require_relative "resources/docker"
require_relative "resources/docker_container"
require_relative "resources/docker_image"
require_relative "resources/docker_plugin"
require_relative "resources/docker_service"
require_relative "resources/elasticsearch"
require_relative "resources/etc_fstab"
require_relative "resources/etc_group"
require_relative "resources/etc_hosts_allow_deny"
require_relative "resources/etc_hosts"
require_relative "resources/file"
require_relative "resources/filesystem"
require_relative "resources/firewalld"
require_relative "resources/gem"
require_relative "resources/groups"
require_relative "resources/grub_conf"
require_relative "resources/host"
require_relative "resources/http"
require_relative "resources/iis_app"
require_relative "resources/iis_app_pool"
require_relative "resources/iis_site"
require_relative "resources/inetd_conf"
require_relative "resources/interface"
require_relative "resources/ip6tables"
require_relative "resources/iptables"
require_relative "resources/kernel_module"
require_relative "resources/kernel_parameter"
require_relative "resources/key_rsa"
require_relative "resources/ksh"
require_relative "resources/limits_conf"
require_relative "resources/login_defs"
require_relative "resources/mount"
require_relative "resources/mssql_session"
require_relative "resources/mysql"
require_relative "resources/mysql_conf"
require_relative "resources/mysql_session"
require_relative "resources/nginx"
require_relative "resources/nginx_conf"
require_relative "resources/npm"
require_relative "resources/ntp_conf"
require_relative "resources/oneget"
require_relative "resources/oracledb_session"
require_relative "resources/os"
require_relative "resources/os_env"
require_relative "resources/package"
require_relative "resources/packages"
require_relative "resources/parse_config"
require_relative "resources/passwd"
require_relative "resources/pip"
require_relative "resources/platform"
require_relative "resources/port"
require_relative "resources/postfix_conf"
require_relative "resources/postgres"
require_relative "resources/postgres_conf"
require_relative "resources/postgres_hba_conf"
require_relative "resources/postgres_ident_conf"
require_relative "resources/postgres_session"
require_relative "resources/powershell"
require_relative "resources/processes"
require_relative "resources/rabbitmq_config"
require_relative "resources/registry_key"
require_relative "resources/security_identifier"
require_relative "resources/security_policy"
require_relative "resources/service"
require_relative "resources/shadow"
require_relative "resources/ssh_config"
require_relative "resources/ssl"
require_relative "resources/sys_info"
require_relative "resources/toml"
require_relative "resources/users"
require_relative "resources/vbscript"
require_relative "resources/virtualization"
require_relative "resources/windows_feature"
require_relative "resources/windows_hotfix"
require_relative "resources/windows_task"
require_relative "resources/wmi"
require_relative "resources/x509_certificate"
require_relative "resources/xinetd_conf"
require_relative "resources/yum"
require_relative "resources/zfs_dataset"
require_relative "resources/zfs_pool"

# file formats, depend on json implementation
require_relative "resources/json"
require_relative "resources/yaml"
require_relative "resources/csv"
require_relative "resources/ini"
require_relative "resources/xml"
