require 'rake/testtask'

desc 'Run lint, unit, and functional tests'
task test: ['test:lint', 'test:unit', 'test:functional']

namespace :test do
  Rake::TestTask.new(:lint) do |t|
    t.description = 'Lint all Ruby files'
    begin
      require 'rubocop/rake_task'
      RuboCop::RakeTask.new(:lint)
    rescue LoadError
      puts 'Please install the `rubocop` gem for lint tests.'
    end
  end

  Rake::TestTask.new(:unit) do |t|
    t.description = 'Run all unit tests'
    t.test_files = FileList['test/unit/**/*_test.rb']
    t.warning = false
    t.verbose = true
  end

  Rake::TestTask.new(:functional) do |t|
    t.description = 'Run all functional tests'
    t.test_files = FileList['test/functional/**/*_test.rb']
    t.warning = true
    t.verbose = true
  end

  task :integration do
    sh('bundle exec kitchen test')
  end
end
