# Main AWS loader file.  The intent is for this to be
# loaded only if AWS resources are needed.

require "aws-sdk-core"

require "aws-sdk-cloudtrail"
require "aws-sdk-cloudwatch"
require "aws-sdk-cloudwatchlogs"
require "aws-sdk-costandusagereportservice"
require "aws-sdk-configservice"
require "aws-sdk-ec2"
require "aws-sdk-ecs"
require "aws-sdk-eks"
require "aws-sdk-elasticloadbalancing"
require "aws-sdk-iam"
require "aws-sdk-kms"
require "aws-sdk-rds"
require "aws-sdk-s3"
require "aws-sdk-sqs"
require "aws-sdk-sns"

require_relative "aws/aws_backend_factory_mixin"
require_relative "aws/aws_resource_mixin"
require_relative "aws/aws_singular_resource_mixin"
require_relative "aws/aws_plural_resource_mixin"
require_relative "aws/aws_backend_base"

# Load all AWS resources
# TODO: loop over and load entire directory
# for f in ls lib/resources/aws/*; do t=$(echo $f | cut -c 5- | cut -f1 -d. ); echo "require '${t}'"; done
require_relative "../resources/aws/aws_billing_report"
require_relative "../resources/aws/aws_billing_reports"
require_relative "../resources/aws/aws_cloudtrail_trail"
require_relative "../resources/aws/aws_cloudtrail_trails"
require_relative "../resources/aws/aws_cloudwatch_alarm"
require_relative "../resources/aws/aws_cloudwatch_log_metric_filter"
require_relative "../resources/aws/aws_config_delivery_channel"
require_relative "../resources/aws/aws_config_recorder"
require_relative "../resources/aws/aws_ec2_instance"
require_relative "../resources/aws/aws_ebs_volume"
require_relative "../resources/aws/aws_ebs_volumes"
require_relative "../resources/aws/aws_flow_log"
require_relative "../resources/aws/aws_ec2_instances"
require_relative "../resources/aws/aws_ecs_cluster"
require_relative "../resources/aws/aws_eks_cluster"
require_relative "../resources/aws/aws_elb"
require_relative "../resources/aws/aws_elbs"
require_relative "../resources/aws/aws_iam_access_key"
require_relative "../resources/aws/aws_iam_access_keys"
require_relative "../resources/aws/aws_iam_group"
require_relative "../resources/aws/aws_iam_groups"
require_relative "../resources/aws/aws_iam_password_policy"
require_relative "../resources/aws/aws_iam_policies"
require_relative "../resources/aws/aws_iam_policy"
require_relative "../resources/aws/aws_iam_role"
require_relative "../resources/aws/aws_iam_root_user"
require_relative "../resources/aws/aws_iam_user"
require_relative "../resources/aws/aws_iam_users"
require_relative "../resources/aws/aws_kms_key"
require_relative "../resources/aws/aws_kms_keys"
require_relative "../resources/aws/aws_rds_instance"
require_relative "../resources/aws/aws_route_table"
require_relative "../resources/aws/aws_route_tables"
require_relative "../resources/aws/aws_s3_bucket"
require_relative "../resources/aws/aws_s3_bucket_object"
require_relative "../resources/aws/aws_s3_buckets"
require_relative "../resources/aws/aws_security_group"
require_relative "../resources/aws/aws_security_groups"
require_relative "../resources/aws/aws_sns_subscription"
require_relative "../resources/aws/aws_sns_topic"
require_relative "../resources/aws/aws_sns_topics"
require_relative "../resources/aws/aws_sqs_queue"
require_relative "../resources/aws/aws_subnet"
require_relative "../resources/aws/aws_subnets"
require_relative "../resources/aws/aws_vpc"
require_relative "../resources/aws/aws_vpcs"
