# .github/workflows/ci-main-pull-request-checks.yml

name: CI Pull Request on Main Branch

on: 
  pull_request:
    branches: [ main, release/** ]
  push:
    branches: [ main, release/** ]
  workflow_dispatch:

permissions:
  contents: read   # default; overridden to write for the SBOM job below

env:
  STUB_VERSION: "1.0.5" 
  
jobs: 
  echo_version:
    name: 'Echo stub version'
    runs-on: ubuntu-latest
    steps:
      - name: echo version of stub and inputs
        run: echo "CI main pull request stub version $STUB_VERSION"

  # Run the org's shared flow; SBOM export to GitHub is ON here.
  call-ci-main-pr-check-pipeline:
    uses: chef/common-github-actions/.github/workflows/ci-main-pull-request.yml@main
    secrets: inherit
    permissions: 
      id-token: write
      contents: write   # needed for GitHub SBOM export (dependency submission)
    with:   
      visibility: ${{ github.event.repository.visibility }}

      # complexity-checks
      perform-complexity-checks: true
      perform-language-linting: true

      # security scanners
      perform-trufflehog-scan: true
      perform-trivy-scan: true

      # Polaris SAST (keep off for this repo; Ruby lib ≠ good Coverity target)
      perform-blackduck-polaris: false
      polaris-application-name: "Chef-Agents"
      polaris-project-name: Chef-Agents-${{ github.event.repository.name }}

      # build/test
      build: true
      unit-tests: false

      # SonarQube
      perform-sonarqube-scan: true
      report-unit-test-coverage: false

      # reporting
      report-to-atlassian-dashboard: true
      quality-product-name: 'InSpec'

      # packaging
      package-binaries: false
      habitat-build: false
      publish-packages: false

      # SBOM + Black Duck SCA (shared workflow)
      generate-sbom: true
      export-github-sbom: true
      perform-blackduck-sca-scan: true
      blackduck-project-group-name: 'Chef-Agents'
      blackduck-project-name: ${{ github.event.repository.name }}
      generate-blackduck-sbom: false
      generate-msft-sbom: false
      license_scout: false

      # 🔧 IMPORTANT: Tweak Detect so policy violations don't fail the job
      # (Use whichever input your shared workflow supports; we pass both safely.)
      blackduck-detect-args: >-
        --detect.policy.check=false
        --detect.detector.required.accuracy.types=RUBYGEMS:LOW
        --detect.tools.excluded=CONTAINER_SCAN,BINARY_SCAN
      detect-args: >-
        --detect.policy.check=false
        --detect.detector.required.accuracy.types=RUBYGEMS:LOW
        --detect.tools.excluded=CONTAINER_SCAN,BINARY_SCAN
