name: Build and Publish Habitat Packages to LTS-2024-Current Channel
on: workflow_dispatch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4