name: Manually Build and Publish Habitat Packages to Custom Channel

on:
  workflow_dispatch:
    inputs:
      habitat_channel:
        description: 'Habitat channel to build and push to'
        required: true
        default: 'LTS-2024'

env:
  BLDR_URL: 'https://bldr.habitat.sh/'
  HAB_ORIGIN: 'chef'
  HAB_AUTH_TOKEN: ${{ secrets.HAB_AUTH_TOKEN }}
  HABITAT_VERSION_SET: 'latest'
  CHEF_LICENSE: "accept-no-persist"
  HAB_LICENSE: "accept-no-persist"
  HAB_NONINTERACTIVE: "true"

permissions:
  contents: write

jobs:
  agent-matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Print OS
        run: echo "--- ${{ matrix.os }}"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: inspec-5

      - name: Install, Build, and Upload Habitat Package (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        shell: bash
        env:
          HAB_REFRESH_CHANNEL: "${{ inputs.habitat_channel }}"
          HAB_BLDR_CHANNEL: "${{ inputs.habitat_channel }}"
        run: |
          echo "--- Installing Habitat on Linux with version: $HABITAT_VERSION_SET"
          curl https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh | sudo bash -s -- -v "$HABITAT_VERSION_SET" -t "x86_64-linux"
          hab license accept
          hab origin key download $HAB_ORIGIN
          hab origin key download --auth $HAB_AUTH_TOKEN --secret $HAB_ORIGIN
          hab pkg build .
          source results/last_build.env
          hab pkg upload --auth $HAB_AUTH_TOKEN results/$pkg_artifact --channel "${{ inputs.habitat_channel }}"
          echo "--- push complete!!"

      - name: Install, Build, and Upload Habitat Package (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        shell: pwsh
        env:
          HAB_REFRESH_CHANNEL: "${{ inputs.habitat_channel }}"
          HAB_BLDR_CHANNEL: "${{ inputs.habitat_channel }}"
        run: |
          Write-Output "--- Installing Habitat on Windows with version: $env:HABITAT_VERSION_SET"
          $env:HAB_LICENSE = "accept-no-persist"
          Invoke-Expression "& { $(Invoke-RestMethod https://raw.githubusercontent.com/habitat-sh/habitat/main/components/hab/install.ps1) } -Version $env:HABITAT_VERSION_SET"
          $env:Path += ";C:\ProgramData\Habitat"
          hab license accept
          hab origin key download $env:HAB_ORIGIN
          hab origin key download --auth $env:HAB_AUTH_TOKEN --secret $env:HAB_ORIGIN
          hab pkg build .
          . results\last_build.ps1
          hab pkg upload results\$pkg_artifact --auth $env:HAB_AUTH_TOKEN --channel "${{ inputs.habitat_channel }}"
          Write-Output "--- push complete!!"
