# This workflow helps to run actions from non-default branches.
name: Promote Habitat Packages to LTS-2024 Channel
on: workflow_dispatch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
