name: "Pull Request Labeler"
on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  triage:
    permissions:
      contents: read  # for actions/labeler to determine modified files
      pull-requests: write  # for actions/labeler to add labels to PRs
    runs-on: ubuntu-latest
    steps:
      - name: Use Git Actions labeler
        uses: actions/labeler@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Fetch pull request base branch
        id: pr_info
        run: |
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          if [ "$BASE_BRANCH" == "main" ]; then
            echo "::set-output name=base_branch_name::inspec-6"
          elif [ "$BASE_BRANCH" == "inspec-4" ] || [ "$BASE_BRANCH" == "inspec-5" ]; then
            echo "::set-output name=base_branch_name::${BASE_BRANCH}"
          else
            echo "Unknown base branch for labelling : ${BASE_BRANCH}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Git API to update labels based on base branch
        if: startsWith(steps.pr_info.outputs.base_branch_name, 'inspec-')
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -d '{"labels":["${{ steps.pr_info.outputs.base_branch_name }}"]}' "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}