name: Promote Habitat Packages

on:
  release:
    types: [published]
    branches:
      - inspec-5

env:
  BLDR_URL: 'https://bldr.habitat.sh/'
  HAB_ORIGIN: 'chef'
  HAB_AUTH_TOKEN: ${{ secrets.HAB_AUTH_TOKEN }}
  HABITAT_VERSION_SET: 'latest'
  CHEF_LICENSE: "accept-no-persist"
  HAB_LICENSE: "accept-no-persist"
  HAB_NONINTERACTIVE: "true"
  SOURCE_CHANNEL: "LTS-2024-current"
  TARGET_CHANNEL: "LTS-2024"

permissions:
  contents: write

jobs:
  promote:
    if: startsWith(github.event.release.tag_name, 'v5.')
    runs-on: ubuntu-latest
    env:
      ORIGIN: chef
      API_URL: https://bldr.habitat.sh/v1/depot/channels

    steps:
      - name: Set VERSION env
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Print tag
        run: |
          echo "Release version: ${{ github.event.release.tag_name }}"
      - name: Get latest Linux package
        id: get_linux
        run: |
          set -euo pipefail
          url="${{ env.API_URL }}/${{ env.ORIGIN }}/${{ env.SOURCE_CHANNEL }}/pkgs/inspec/${VERSION}/latest?target=x86_64-linux"
          echo "Requesting: $url"
          response=$(curl -s "$url")
          if echo "$response" | grep -q '^{'; then
            ident=$(echo "$response" | jq -r '.ident.origin + "/" + .ident.name + "/" + .ident.version + "/" + .ident.release')
            echo "linux_pkg=$ident" >> "$GITHUB_OUTPUT"
          else
            echo "Linux package not found or invalid response"
            echo "$response"
            exit 1
          fi

      - name: Get latest Windows package
        id: get_windows
        run: |
          set -euo pipefail
          url="${{ env.API_URL }}/${{ env.ORIGIN }}/${{ env.SOURCE_CHANNEL }}/pkgs/inspec/${VERSION}/latest?target=x86_64-windows"
          echo "Requesting: $url"
          response=$(curl -s "$url")
          if echo "$response" | grep -q '^{'; then
            ident=$(echo "$response" | jq -r '.ident.origin + "/" + .ident.name + "/" + .ident.version + "/" + .ident.release')
            echo "windows_pkg=$ident" >> "$GITHUB_OUTPUT"
          else
            echo "Windows package not found or invalid response"
            echo "$response"
            exit 1
          fi

      - name: Install Habitat CLI
        run: |
          echo "--- Installing Habitat on Linux with version: $HABITAT_VERSION_SET"
          curl https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh | sudo bash -s -- -v "$HABITAT_VERSION_SET" -t "x86_64-linux"
          hab license accept
          hab origin key download $HAB_ORIGIN
          hab origin key download --auth $HAB_AUTH_TOKEN --secret $HAB_ORIGIN

      - name: Promote Linux package
        run: |
          hab pkg promote ${{ steps.get_linux.outputs.linux_pkg }} ${{ env.TARGET_CHANNEL }} --auth="${{ secrets.HAB_AUTH_TOKEN }}"
        env:
          HAB_LICENSE: accept-no-persist

      - name: Promote Windows package
        run: |
          hab pkg promote ${{ steps.get_windows.outputs.windows_pkg }} ${{ env.TARGET_CHANNEL }} --auth="${{ secrets.HAB_AUTH_TOKEN }}"
        env:
          HAB_LICENSE: accept-no-persist